# Generated by Django 5.1.6 on 2025-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('interests', models.TextField()),
                ('about', models.TextField()),
                ('profile_picture', models.URLField()),
            ],
        ),
    ]
