# Generated by Django 5.1.6 on 2025-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='profile_picture',
            field=models.ImageField(upload_to='user_pictures/'),
        ),
    ]
